export const formatProgram = ({
  schoolName,
  programName,
  department,
  country,
  funding,
  fundingAmount,
  deadline,
  greWaiver,
  ieltsWaiver,
  appFeeWaiver,
  requiredDocs,
  applicationLink,
  professors,
  source,
}) => ({
  schoolName: schoolName || "Unknown University",
  programName: programName || "Unknown Program",
  department: department || "N/A",
  country: country || "N/A",
  funding: funding || "N/A",
  fundingAmount: fundingAmount || "N/A",
  deadline: deadline || null,
  greWaiver: greWaiver || false,
  ieltsWaiver: ieltsWaiver || false,
  appFeeWaiver: appFeeWaiver || false,
  requiredDocs: requiredDocs || [],
  applicationLink: applicationLink || "",
  professors: professors || [],
  source: source || "Unknown",
});
